name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - name: 📦 Install packages
        run: bun install --frozen-lockfile
      - name: 💅 Format check
        run: bun run format:check
      - name: 🆎 Lint + TypeCheck
        run: bun run lint
      - name: 🧪 Run tests
        run: bun test
      - name: 🏗️ Build
        run: bun run build
